In [11]:
import pandas as pd
import numpy as np
factbook = pd.read_csv("Datasets/factbook.csv")
for c in factbook.columns:
    if factbook[c].dtype == object:
        factbook[c]=factbook[c].str.replace("[$,)]", "")
        factbook[c]=factbook[c].str.replace("(","-")
        try:

            factbook[c]=factbook[c].astype(float)
        except:
            pass
        

        
factbook.shape

(149, 29)

In [12]:
factbook

,Country,Area,Birth rate,Current account balance,Death rate,Electricity consumption,Electricity production,Exports,GDP,GDP per capita,...,Life expectancy at birth,Military expenditures,Natural gas consumption,Oil consumption,Population,Public debt,Railways,Reserves of foreign exchange & gold,Total fertility rate,Unemployment rate
0,Japan,377835.0,9.47,1.702000e+11,8.95,9.710000e+11,1.044000e+12,5.388000e+11,3.745000e+12,29400.0,...,81.15,1.00,80420000000.00,5290000.0,127417244.0,164.3,23705,664600000000.00,1.39,4.7
1,Germany,357021.0,8.33,7.359000e+10,10.55,5.195000e+11,5.600000e+11,8.933000e+11,2.362000e+12,28700.0,...,78.65,1.50,99550000000.00,2891000.0,82431390.0,65.8,46039,96840000000.00,1.39,10.6
2,Saudi Arabia,1960582.0,29.56,5.150000e+10,2.62,1.285000e+11,1.382000e+11,1.130000e+11,3.102000e+11,12000.0,...,75.46,10.00,56400000000.00,1550000.0,26417599.0,75,1392,23620000000.00,4.05,25
3,Russia,17075200.0,9.80,4.604000e+10,14.52,8.943000e+11,9.150000e+11,1.625000e+11,1.408000e+12,9800.0,...,67.10,,405800000000.00,2310000.0,143420309.0,28.2,87157,124500000000.00,1.27,8.3
4,Switzerland,41290.0,9.77,4.095000e+10,8.48,5.453000e+10,6.347000e+10,1.307000e+11,2.519000e+11,33800.0,...,80.39,1.00,3093000000.00,290400.0,7489370.0,57.2,4533,69580000000.00,1.42,3.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144,Italy,301230.0,8.89,-2.110000e+10,10.30,2.939000e+11,2.616000e+11,3.364000e+11,1.609000e+12,27700.0,...,79.68,1.80,71180000000.00,1866000.0,58103033.0,105.6,19507,61500000000.00,1.28,8.6
145,Spain,504782.0,10.10,-3.089000e+10,9.63,2.184000e+11,2.290000e+11,1.725000e+11,9.376000e+11,23300.0,...,79.52,1.20,17960000000.00,1497000.0,40341462.0,53.2,14268,19700000000.00,1.28,10.4
146,United Kingdom,244820.0,10.78,-3.346000e+10,10.18,3.374000e+11,3.959000e+11,3.472000e+11,1.782000e+12,29600.0,...,78.38,2.40,92850000000.00,1692000.0,60441457.0,39.6,17186,48730000000.00,1.66,4.8
147,Australia,7686850.0,12.26,-3.830000e+10,7.44,1.956000e+11,2.103000e+11,8.689000e+10,6.117000e+11,30700.0,...,80.39,2.70,23330000000.00,796500.0,20090437.0,17.4,43802,35140000000.00,1.76,5.1
148,United States,9631418.0,14.14,-6.465000e+11,8.25,3.660000e+12,3.839000e+12,7.950000e+11,1.175000e+13,40100.0,...,77.71,3.30,640900000000.00,19650000.0,295734134.0,65,228464,85940000000.00,2.08,5.5

In [18]:
from bokeh.io import curdoc, show
from bokeh.models import ColumnDataSource, Grid, LinearAxis, Plot, Scatter

source = ColumnDataSource(factbook.to_dict(orient="list"))

plot = Plot(
    title=None, width=300, height=300,
    min_border=0, toolbar_location=None)

glyph = Scatter(x="GDP per Capita", y="Life expectancy", size=20, fill_color="#74add1")
plot.add_glyph(source, glyph)

xaxis = LinearAxis()
plot.add_layout(xaxis, 'below')

yaxis = LinearAxis()
plot.add_layout(yaxis, 'left')

plot.add_layout(Grid(dimension=0, ticker=xaxis.ticker))
plot.add_layout(Grid(dimension=1, ticker=yaxis.ticker))

curdoc().add_root(plot)

show(plot)

ERROR:bokeh.core.validation.check:E-1001 (BAD_COLUMN_NAME): Glyph refers to nonexistent column name. This could either be due to a misspelling or typo, or due to an expected column being missing. : key "x" value "GDP per Capita" (closest match: "GDP per capita"), key "y" value "Life expectancy" (closest match: "Life expectancy at birth") [renderer: GlyphRenderer(id='1300', ...)]